FROM local/fastdronexi35:orin_base_35.3.1

ARG ROS_VERSION=noetic
ENV OPENCV_VERSION=4.5.4
ENV FDRONE_WS=/root/Fast-Drone-XI35

SHELL ["bash", "-c", "-l"]

# Clone Fast-Drone-XI35
RUN  git config --global http.lowSpeedLimit 0 && \
     git config --global http.lowSpeedTime 999999 && \
     git config --global http.postBuffer 1024288000 && \
     # optional : set http proxy if unable to successfully execute git clone
     # git config --global http.proxy 192.168.31.6:7897 && \
     # git config --global https.proxy 192.168.31.6:7897 && \
     cd /root && git clone https://github.com/Longer95479/Fast-Drone-XI35.git -b board
WORKDIR ${FDRONE_WS}

# container init
COPY ./container_init.sh /
COPY ./daemon /daemon
RUN  chmod +x /container_init.sh
ENTRYPOINT ["/bin/bash", "/container_init.sh"]
